# Generated by Django 5.0 on 2024-05-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('drug_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('Formulation', models.CharField(max_length=250)),
                ('cost', models.FloatField()),
                ('quantity_in_stock', models.IntegerField()),
            ],
        ),
    ]
