# Generated by Django 5.0 on 2024-04-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=8)),
                ('appointment_time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('checkin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('isappointment', models.BooleanField(default=False)),
                ('doctor_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticTests',
            fields=[
                ('test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('test_date', models.DateField()),
                ('test_results', models.CharField(max_length=200)),
                ('condition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicalcondition')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalNotes',
            fields=[
                ('note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note_date', models.DateField()),
                ('note', models.TextField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Surgeries',
            fields=[
                ('surgery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('surgery_name', models.CharField(max_length=200)),
                ('surgery_date', models.DateField()),
                ('condition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicalcondition')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
            ],
        ),
    ]
