# Generated by Django 5.0 on 2024-04-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_processes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgeries',
            name='condition_id',
        ),
        migrations.RemoveField(
            model_name='surgeries',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='surgeries',
            name='surgeon',
        ),
        migrations.DeleteModel(
            name='MedicalNotes',
        ),
        migrations.DeleteModel(
            name='Surgeries',
        ),
    ]
