# Generated by Django 5.0 on 2024-05-01 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('patient', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('allergy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('allergen', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('High', 'high'), ('Moderate', 'moderate'), ('Low', 'low')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('hospitalization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=200)),
                ('bed', models.CharField(max_length=200)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('immunization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vaccine', models.CharField(max_length=200)),
                ('admission_date', models.DateField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('condition_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_recorded', models.DateField()),
                ('diagnosis', models.CharField(max_length=200)),
                ('treatment', models.CharField(max_length=200)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('prescription', models.ManyToManyField(max_length=200, to='inventory.drugs')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_prescribed', models.DateField()),
                ('dosage', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.CharField(max_length=200)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
                ('drug_name', models.ManyToManyField(max_length=200, to='inventory.drugs')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('pharmacist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.pharmacist')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('vital_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_recorded', models.DateField()),
                ('temperature', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('blood_pressure', models.CharField(max_length=200)),
                ('nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.nurse')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
