# Generated by Django 5.0 on 2024-04-29 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalNotes',
            fields=[
                ('note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note_date', models.DateField()),
                ('note', models.TextField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Surgeries',
            fields=[
                ('surgery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('surgery_name', models.CharField(max_length=200)),
                ('surgery_date', models.DateField()),
                ('condition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicalcondition')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
            ],
        ),
    ]
