# Generated by Django 5.0 on 2024-05-01 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeries',
            name='condition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditions.medicalcondition'),
        ),
    ]
