# Generated by Django 5.0 on 2024-04-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('res_address', models.CharField(max_length=200)),
                ('registrar', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_prescribed', models.DateField()),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.CharField(max_length=200)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
                ('pharmacist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.pharmacist')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('condition_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_recorded', models.DateField()),
                ('diagnosis', models.CharField(max_length=200)),
                ('treatment', models.CharField(max_length=200)),
                ('prescription', models.CharField(max_length=200)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('immunization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vaccine', models.CharField(max_length=200)),
                ('admission_date', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('hospitalization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=200)),
                ('bed', models.CharField(max_length=200)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('allergy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('allergen', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('High', 'high'), ('Moderate', 'moderate'), ('Low', 'low')], max_length=20)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('vital_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_recorded', models.DateField()),
                ('temperature', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('blood_pressure', models.CharField(max_length=200)),
                ('nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.nurse')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
