# Generated by Django 5.0 on 2024-05-01 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
        ('doctor', '0002_alter_surgeries_condition_id'),
        ('hospital_processes', '0003_alter_diagnostictests_condition_id'),
        ('patient', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalization',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='medicalcondition',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='medicalcondition',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='pharmacist_id',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='nurse_id',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='conditions.allergies'),
        ),
        migrations.AddField(
            model_name='patient',
            name='immunizations',
            field=models.ManyToManyField(blank=True, to='conditions.immunization'),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('Checked In', 'Checked In'), ('Admitted', 'Admitted'), ('Under Observation', 'Under Observation'), ('Discharged', 'Discharged'), ('Transferred', 'Transferred'), ('Surgery', 'Surgery'), ('Recovery', 'Recovery'), ('Emergency', 'Emergency'), ('Outpatient', 'Outpatient'), ('Deceased', 'Deceased')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registrar',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.DeleteModel(
            name='Allergies',
        ),
        migrations.DeleteModel(
            name='Hospitalization',
        ),
        migrations.DeleteModel(
            name='Immunization',
        ),
        migrations.DeleteModel(
            name='MedicalCondition',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Vitals',
        ),
    ]
