# Generated by Django 4.1.5 on 2024-02-17 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserViews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registrar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
