# Generated by Django 4.1.5 on 2024-02-17 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserViews', '0004_rename_registrar_id_patient_registrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='registrar',
        ),
    ]
