# Generated by Django 4.1.5 on 2024-02-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserViews', '0007_rename_registrar_id_patient_registrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registrar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
