# Generated by Django 4.1.5 on 2024-02-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserViews', '0008_alter_patient_registrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
