# Generated by Django 5.0 on 2024-04-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FrontDeskExecutive',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('speciality', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.cashier')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
                ('front_desk_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.frontdeskexecutive')),
                ('lab_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.labtechnician')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.nurse')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.pharmacist')),
            ],
        ),
    ]
